# Generated by Django 4.1.2 on 2022-10-16 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_thing_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thing',
        ),
    ]
