# Generated by Django 4.1.2 on 2022-10-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='age',
        ),
        migrations.AddField(
            model_name='thing',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
